config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :signs
  # resources :callbacks

  root 'signs#index'

  post '/' => 'signs#index'

  get '/callbacks' => 'callbacks#index'
  post '/callbacks' => 'callbacks#create'

  get 'account' => 'accounts#get_account'
  post 'update-account' => 'accounts#update_account'
  post 'verify-account' => 'accounts#verify_account'

  get 'signature-request' => 'signs#signature_request'
  get 'all-requests' => 'signs#all_requests'
  post 'send-request' => 'signs#send_request'
  get 'template-request' => 'signs#template_request'
  get 'unclaimed-draft' => 'signs#unclaimed_draft'

  post 'reminder' => 'signs#reminder'
  get 'update-email' => 'signs#update_email'
  post 'cancel' => 'signs#cancel'

  get 'file' => 'signs#file'

  get '/embeddeds' => 'embeddeds#index'
  get '/embeddeds/template' => 'embeddeds#template'
  get '/embeddeds/file-request' => 'embeddeds#file_request'
  get '/embeddeds/unclaimed-draft' => 'embeddeds#unclaimed_draft'
  get '/embeddeds/unclaimed-draft-template' => 'embeddeds#unclaimed_draft_template'
  get '/embeddeds/template-draft' => 'embeddeds#template_draft'
  get '/embeddedds/edit-unclaimed-draft' => 'embeddeds#edit_unclaimed_draft'

  get '/templates/info' => 'templates#get_template'
  get '/templates/update' => 'templates#update'
  get '/templates/list' => 'templates#list'
  post '/templates/add-access' => 'templates#add_access'
  post '/templates/remove-access' => 'templates#remove_access'
  post '/templates/delete' => 'templates#delete'
  get '/templates/download' => 'templates#download'

  get '/teams' => 'teams#index'
  post '/teams/new' => 'teams#new'
  post '/teams/update' => 'teams#update'
  post '/teams/add-user' => 'teams#add_user'

  get '/apps/info' => 'apps#info'
  get '/apps/list' => 'apps#list'
  get '/apps/create' => 'apps#create'
  get '/apps/update' => 'apps#update'
  get '/apps/delete' => 'apps#delete'

  get '/helloworks' => 'helloworks#index'
  post '/helloworks' => 'helloworks#create'
  get '/helloworks/new' => 'helloworks#new_instance'
  post '/helloworks/new' => 'helloworks#new_instance'

  get '/helloworks/v3/new' => 'helloworks#v3_instance'
end

app/models/sign.rb
class Sign < ApplicationRecord
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :client

  def index

    # @response = params
    # event = @response["json"]
    # object = JSON.parse(event, symbolize_names: true)
    # p "***** EVENT TYPE"
    # p event_type = object[:event][:event_type]

    # client = Sign.initiate_client
  end

  def signature_request
    request = client.get_signature_request :signature_request_id => params[:request_id]
    data = JSON.parse(request.to_json, symbolize_names: true)
    id = data[:raw_data][:signatures][0][:signature_id]
    render json: request
  end

  def all_requests
    @signatures = client.get_signature_requests
    # @headers = @signatures.headers
    # p @signatures
    render json: @signatures
  end

  def send_request
    # file = File.join(Rails.root, 'app', 'text_tag.pdf')

    response = client.send_signature_request(
      :test_mode => 1,
      :title => 'Test Contract',
      :subject => 'Test Signature Request',
      :message => 'This is a test from my Rails app',
      :signers => [
        {
          :email_address => ENV["EMAIL"],
          :name => 'Jen'
        }
      ],
      :use_text_tags => 1,
      # :hide_text_tags => 1,
    #   :files => ['/Users/jenyoung/Documents/Testing/Rails-Test/app/assets/doc1.pdf', '/Users/jenyoung/Documents/Testing/Rails-Test/app/assets/doc2.pdf']
    # )
      # :form_fields_per_document => [
      #   	[{
      #   		"api_id": "test",
      #   		"name": "hi",
      #   		"type": "signature",
      #   		"x": 0,
      #   		"y": 52,
      #   		"height": 30,
      #   		"width": 20,
      #   		"required": true,
      #   		"signer": 0,
      #   		"page": 1
      #   	}],
      #     [{
      #       "api_id": "secondDoc",
      #       "name": "secondPage",
      #       "type": "text",
      #       "x": 50,
      #       "y": 52,
      #       "height": 30,
      #       "width": 20,
      #       "required": true,
      #       "signer": 0,
      #       "page": 1
      #     }]
      #   ],
        :files => ['public/Text_Tags_Merge.pdf'],
        :custom_fields => [
          {"name": "address", "value": "PSYDUCK"}
        ]
        # :file_urls => ['http://www.pdf995.com/samples/pdf.pdf', 'http://www.africau.edu/images/default/sample.pdf']
    )


    data = JSON.parse(response.to_json, symbolize_names: true)
    id = data[:raw_data][:signatures][0][:signature_id]

    p id
    #
    render json: response
  end

  def template_request
    request = client.send_signature_request_with_template(
        :test_mode => 1,
        :template_id => '51d63d2b4c9f4740e6096e5100df26a82a02612b',
        :subject => 'Offer Letter',
        :message => 'Glad we could come to an agreement.',
        :signers => [
            # {
            #     :email_address => 'jyoung488@gmail.com',
            #     :name => 'Jen Candidate',
            #     :role => 'Candidate'
            # },
            {
                :email_address => 'jyoung488+1@gmail.com',
                :name => 'Jen Hiring Manager',
                :role => 'Hiring Manager'
            }
        ]
      # :files => ['/Users/jenyoung/Documents/Testing/Rails-Test/app/assets/doc1.pdf', '/Users/jenyoung/Documents/Testing/Rails-Test/app/assets/doc2.pdf']

    )
    p request.warnings
    flash[:notice] = "Request sent"
    redirect_to root_path
  end

  def reminder
    client.remind_signature_request :signature_request_id => params[:signature_id], :email_address => params[:email]

    redirect_to root_path
  end

  def update_email
    client.update_signature_request(
        :signature_request_id => '33e7a1d839e98797d633fb8b47247c4aa9a5936d',
        :signature_id => '5064ca698bde9581ad75f6d62450eb4b',
        :email_address => 'jen.young+1@hellosign.com'
        )
  end

  def cancel
    client.cancel_signature_request :signature_request_id => params[:request_id]

    redirect_to root_path
  end

  def file
    file_bin = client.signature_request_files :signature_request_id => params[:request_id], :file_type => 'zip'

    File.open("without-attachment.zip", "wb") do |file|
      file.write(file_bin)
    end
  end

  def unclaimed_draft
    draft = client.create_unclaimed_draft(
      test_mode: 1,
      type: 'request_signature',
      # file_url: 'http://www.pdf995.com/samples/pdf.pdf',
      signers: [
          email_address: 'jen.young+2@hellosign.com',
          name: "Ruby HelloSign",
      ],
      :files => ['public/Text_Tags_Merge.pdf'],
      :custom_fields => [
        {"name": "address", "value": "PSYDUCK"}
      ],
      :use_text_tags => 1
      # form_fields_per_document: [
      #   [
      #     {
      #       "api_id": "uniqueID",
      #       "name": "TextFieldName",
      #       "type": "signature",
      #       "x": 30,
      #       "y": 52,
      #       "height": 30,
      #       "width": 100,
      #       "required": true,
      #       "signer": 0,
      #       "page": 1
      #     }
      #   ]
      # ]
    )

    redirect_to draft.claim_url
  end

end

app/views/signs/all_requests.html.erb
<%= @signatures%>

app/views/signs/index.html.erb
<h1>HelloSign Test App</h1>
<div id="links">
  <%= @response %>
  <h4>Account</h4>
  <ul>
    <li>
      <%= link_to 'Get Account', account_path %>
    </li>
    <li>
      Update Account:
      <%= form_tag("/update-account", method: "post") do %>
      <%= text_field_tag(:callback_url, nil, :placeholder => 'Callback URL') %>
      <%= submit_tag("Update Account") %>
      <% end %>
    </li>
    <li>
      Verify Account:
      <%= form_tag("/verify-account", method: "post") do %>
      <%= text_field_tag(:email, nil, :placeholder => 'Email') %>
      <%= submit_tag("Verify Account") %>
      <% end %>
    </li>
  </ul>
  <h4>Non-Embedded Signature Requests</h4>
  <ul>
    <li>
      <%= form_tag("/signature-request", method: "get") do %>
      <%= text_field_tag(:request_id, nil, :placeholder => 'Request ID') %>
      <%= submit_tag("Signature Request Info") %>
      <% end %>
    </li>
    <li>
      <%= link_to 'All Signature Requests', all_requests_path %>
    </li>
    <li>
      <%= link_to 'Send Signature Request', send_request_path, method: "post" %>
    </li>
    <li>
      <%= link_to 'Update Signature Request', update_email_path %>
    </li>
    <li>
      <%= link_to 'Send Request via Template', template_request_path %>
    </li>
    <li>Send Reminder:
      <%= form_tag("/reminder", method: "post") do %>
        <%= text_field_tag(:signature_id, nil, :placeholder => 'Signature ID') %>
        <%= text_field_tag(:email, nil, :placeholder => 'Email') %>
        <%= submit_tag("Send Reminder") %>
      <% end %>
    </li>
    <li>Update Email:
      <%= form_tag("/update-email", method: "post") do %>
        <%= text_field_tag(:signature_request_id, nil, :placeholder => 'Signature Request ID') %>
        <%= text_field_tag(:signature_id, nil, :placeholder => 'Signature ID') %>
        <%= text_field_tag(:new_email, nil, :placeholder => 'New Email') %>
        <%= submit_tag("Update Email") %>
      <% end %>
    </li>
    <li>Cancel Signature Request:
      <%= form_tag("/cancel", method: "post") do %>
        <%= text_field_tag(:request_id, nil, :placeholder => 'Request ID') %>
        <%= submit_tag("Cancel Signature Request") %>
      <% end %>
    </li>
    <li>
      Download File:
      <%= form_tag("/file", method: "get") do %>
        <%= text_field_tag(:request_id, nil, :placeholder => 'Request ID') %>
        <%= submit_tag("Get File") %>
      <% end %>
    </li>
    <li>
      <%= link_to 'Create Unclaimed Draft', unclaimed_draft_path %>
    </li>
  </ul>
  <h4>Templates</h4>
  <ul>
    <li>
      <%= form_tag("/templates/info", method: "get") do %>
        <%= text_field_tag(:template_id, nil, :placeholder => 'Template ID') %>
        <%= submit_tag("Get Template") %>
      <% end %>
    </li>
    <li>
      <%= link_to 'Update Template', templates_update_path %>
    </li>
    <li>
      <%= link_to 'List Templates', templates_list_path %>
    </li>
    <li>
      <%= form_tag("/templates/add-access", method: "post") do %>
        <%= text_field_tag(:template_id, nil, :placeholder => 'Template ID') %>
        <%= text_field_tag(:email, nil, :placeholder => 'Email') %>
        <%= submit_tag("Add User Access") %>
      <% end %>
    </li>
    <li>
      <%= form_tag("/templates/remove-access", method: "post") do %>
        <%= text_field_tag(:template_id, nil, :placeholder => 'Template ID') %>
        <%= text_field_tag(:email, nil, :placeholder => 'Email') %>
        <%= submit_tag("Remove User Access") %>
      <% end %>
    </li>
    <li>
      <%= form_tag("/templates/delete", method: "post") do %>
        <%= text_field_tag(:template_id, nil, :placeholder => 'Template ID') %>
        <%= submit_tag("Delete Template") %>
      <% end %>
    </li>
    <li>
      Download Template Files:
      <%= form_tag("/templates/download", method: "get") do %>
        <%= text_field_tag(:template_id, nil, :placeholder => 'Template ID') %>
        <%= submit_tag("Get Template File") %>
      <% end %>
    </li>
  </ul>
  <h4>Team</h4>
  <ul>
    <li>
      <%= link_to 'Get Team', teams_path %>
    </li>
    <li>
      <%= form_tag("/teams/new", method: "post") do %>
        <%= text_field_tag(:name, nil, :placeholder => 'Team Name') %>
        <%= submit_tag("Create Team") %>
      <% end %>
    </li>
    <li>
      <%= form_tag("/teams/update", method: "post") do %>
        <%= text_field_tag(:name, nil, :placeholder => 'Team Name') %>
        <%= submit_tag("Update Team") %>
      <% end %>
    </li>
    <li>
      <%= form_tag("/teams/add-user", method: "post") do %>
        <%= text_field_tag(:email, nil, :placeholder => 'Email') %>
        <%= submit_tag("Add User to Team") %>
      <% end %>
    </li>
  </ul>
  <h4>API Apps</h4>
  <ul>
    <li>
      <%= form_tag("/apps/info", method: "get") do %>
        <%= text_field_tag(:client_id, nil, :placeholder => 'Client ID') %>
        <%= submit_tag("Get API App") %>
      <% end %>
    </li>
    <li>
      <%= link_to 'List API Apps', apps_list_path %>
    </li>
    <li>
      <%= form_tag("/apps/create", method: "get") do %>
        <%= text_field_tag(:app_name, nil, :placeholder => 'App Name') %>
        <%= submit_tag("Create API App") %>
      <% end %>
    </li>
    <li>
      <%= form_tag("/apps/update", method: "get") do %>
        <%= text_field_tag(:client_id, nil, :placeholder => 'Client ID') %>
        <%= text_field_tag(:app_name, nil, :placeholder => 'App Name') %>
        <%= submit_tag("Update API App") %>
      <% end %>
    </li>
    <li>
      <%= form_tag("/apps/delete", method: "get") do %>
        <%= text_field_tag(:client_id, nil, :placeholder => 'Client ID') %>
        <%= submit_tag("Delete API App") %>
      <% end %>
    </li>
  </ul>
</div>
<div id="embedded">
  <h4>Embedded Endpoints</h4>
  <ul>
    <li>
      <%= link_to 'Embedded Signatures', embeddeds_path %>
    </li>
  <ul>
</div>
<div>
  <h4>HelloWorks</h4>
  <ul>
    <li>
      <%= link_to 'Create new HelloWorks Instance', helloworks_new_path, method: :post %>
    </li>
    <li>
      <%= link_to 'v3 HelloWorks Instance', helloworks_v3_new_path %>
    </li>
  </ul>
</div>

app/views/signs/update_email.html.erb
<%= link_to 'update_signature_request', 'https://app.hellosign.com/api/reference#update_signature_request', target: "_blank" %> method coming soon!