config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :signs
  # resources :callbacks

  root 'signs#index'

  post '/' => 'signs#index'

  get '/callbacks' => 'callbacks#index'
  post '/callbacks' => 'callbacks#create'

  get 'account' => 'accounts#get_account'
  post 'update-account' => 'accounts#update_account'
  post 'verify-account' => 'accounts#verify_account'

  get 'signature-request' => 'signs#signature_request'
  get 'all-requests' => 'signs#all_requests'
  post 'send-request' => 'signs#send_request'
  get 'template-request' => 'signs#template_request'
  get 'unclaimed-draft' => 'signs#unclaimed_draft'

  post 'reminder' => 'signs#reminder'
  get 'update-email' => 'signs#update_email'
  post 'cancel' => 'signs#cancel'

  get 'file' => 'signs#file'

  get '/embeddeds' => 'embeddeds#index'
  get '/embeddeds/template' => 'embeddeds#template'
  get '/embeddeds/file-request' => 'embeddeds#file_request'
  get '/embeddeds/unclaimed-draft' => 'embeddeds#unclaimed_draft'
  get '/embeddeds/unclaimed-draft-template' => 'embeddeds#unclaimed_draft_template'
  get '/embeddeds/template-draft' => 'embeddeds#template_draft'
  get '/embeddedds/edit-unclaimed-draft' => 'embeddeds#edit_unclaimed_draft'

  get '/templates/info' => 'templates#get_template'
  get '/templates/update' => 'templates#update'
  get '/templates/list' => 'templates#list'
  post '/templates/add-access' => 'templates#add_access'
  post '/templates/remove-access' => 'templates#remove_access'
  post '/templates/delete' => 'templates#delete'
  get '/templates/download' => 'templates#download'

  get '/teams' => 'teams#index'
  post '/teams/new' => 'teams#new'
  post '/teams/update' => 'teams#update'
  post '/teams/add-user' => 'teams#add_user'

  get '/apps/info' => 'apps#info'
  get '/apps/list' => 'apps#list'
  get '/apps/create' => 'apps#create'
  get '/apps/update' => 'apps#update'
  get '/apps/delete' => 'apps#delete'

  get '/helloworks' => 'helloworks#index'
  post '/helloworks' => 'helloworks#create'
  get '/helloworks/new' => 'helloworks#new_instance'
  post '/helloworks/new' => 'helloworks#new_instance'

  get '/helloworks/v3/new' => 'helloworks#v3_instance'
end

app/models/embedded.rb
class Embedded < ApplicationRecord
end

app/controllers/embeddeds_controller.rb
class EmbeddedsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :client

  def index
  end

  def template
    email = "george@example.com"
    name = "George",
    role = "Dispensary Owner or Manager"
    request = client.create_embedded_signature_request_with_template(
      :test_mode => 1,
      :client_id => ENV['CLIENT_ID'],
      :template_id => '75483a9f0674c1b23fbc42ae8006a0b73fd36736',
      :file_url => 'http://www.pdf995.com/samples/pdf.pdf',
      :allow_decline => 1,
      :message => 'Glad we could come to an agreement.',
      signers: [
          {
              email_address: "#{email}",
              name: "#{name}",
              role: 'Client'
          }
      ],

      :custom_fields => [
        {
          name: "Address",
          value: "123 Main St."
        }
      ]
    )
    p request
    signatures = request.signatures

    url_request = client.get_embedded_sign_url :signature_id => signatures[0].signature_id
    p "****"
    p url_request
    @sign_url = url_request.sign_url
  end

  def file_request
    request = client.create_embedded_signature_request(
      :test_mode => 1,
      :client_id => ENV['CLIENT_ID'],
      :subject => 'test subject',
      :message => 'Rails Embedded Signature Request',
      :signers => [
        {
          :email_address => 'jyoung488@gmail.com',
          :name => 'Jen Rails'
        }
      ],
      :use_text_tags => 1,
      :hide_text_tags => 1,
      :files => ['public/Text_Tags_Merge.pdf'],
      :custom_fields => [
        {"name": "address", "value": "PSYDUCK"}
      ]
      # :files => ['/Users/jenyoung/Documents/Testing/Rails-Test/app/assets/doc1.pdf', '/Users/jenyoung/Documents/Testing/Rails-Test/app/assets/doc2.pdf']
      # :file_url => 'http://www.pdf995.com/samples/pdf.pdf'
    )

    p request

    signatures = request.signatures

    url_request = client.get_embedded_sign_url :signature_id => signatures[0].signature_id
    @sign_url = url_request.sign_url
  end

  def unclaimed_draft
    request = client.create_embedded_unclaimed_draft(
        test_mode: 1,
        # :file_url => 'http://www.pdf995.com/samples/pdf.pdf',
        client_id: ENV['CLIENT_ID'],
        files: ['public/Text_Tags_Merge.pdf'],
        signers: [
          {
            'email_address' => ENV["EMAIL"],
            'name' => 'Jen'
          },
          {
            'email_address' => "jen@test.com",
            'name' => "Jen Second Signer",
          }
        ],
        subject: 'Your signature is required',
        requester_email_address: ENV['EMAIL'],
        :type => "request_signature",
        # :custom_fields => [
        #   {"name": "address", "value": "PSYDUCK"}
        # ],
        # :use_text_tags => 1
        # :form_fields_per_document => [
          #   [{
          #     "api_id": "test",
          #     "name": "hi",
          #     "type": "signature",
          #     "x": 0,
          #     "y": 52,
          #     "height": 30,
          #     "width": 20,
          #     "required": true,
          #     "signer": 0,
          #     "page": 1
          #   }]
          # ]
    )

    @sign_url = request.claim_url
  end

  def unclaimed_draft_template
    request = client.create_embedded_unclaimed_draft_with_template(
      :test_mode => 1,
      :client_id => ENV['CLIENT_ID'],
      :requester_email_address => ENV['EMAIL'],
      :template_id => '1159636818bce0549c40d3477a937da0abb1b92a',
      :message => 'Glad we could come to an agreement.',
      :signers => [
          {
              :email_address => "jyoung488@gmail.com",
              :name => "Jen Test",
              :role => "Client"
          }
      ],
      # :custom_fields => [
      #   {
      #     :name => "Name",
      #     :value => "SDK TEST"
      #   }
      # ]
    )

    @sign_url = request.claim_url
  end

  def template_draft
    request = client.create_embedded_template_draft(
      :test_mode => 1,
      :client_id => ENV['CLIENT_ID'],
      :file_url => 'http://www.pdf995.com/samples/pdf.pdf',
      :title => 'Embedded Template Draft from Rails',
      :signer_roles => [
        {
          :name => 'Cient',
          :order => 0
        },
        {
          :name => 'Manager',
          :order => 1
        }
      ]
    )

    @sign_url = request.edit_url
  end

  def edit_unclaimed_draft
    @draft = client.edit_and_resend_unclaimed_draft(
      :signature_request_id => '596e1b9288c7c726c603fc3080689e6c89c1a397',
      :client_id => ENV['CLIENT_ID'],
      :test_mode => true
    )
    p "***"

    @sign_url = @draft.claim_url
  end

end

app/views/embeddeds/_iframe.html.erb
<h1 id="event">
  HelloSign Signature Request
</h1>
<script type="text/javascript">
  var signUrl = "<%= sign_url %>";
  var clientId = "<%= ENV['CLIENT_ID'] %>";

  HelloSign.init(clientId);
  HelloSign.open({
    url: signUrl,
    debug: true,
    allowCancel: false,
    skipDomainVerification: true,
    uxVersion: 2,
    messageListener: function(eventData){
      console.log("hi");
      HelloSign.close()
      if (eventData.event == 'signature_request_canceled') {
        document.getElementById("event").innerHTML = "SIGNATURE CANCELLED"
      } else if (eventData.event == 'signature_request_signed') {
        console.log(eventData);
      } else if (eventData.event == 'signature_request_declined') {
        console.log(eventData);
      }
    }
  })
</script>

app/views/embeddeds/edit_unclaimed_draft.html.erb
<%= render :partial => 'embeddeds/iframe', locals: { sign_url: @sign_url } %>

app/views/embeddeds/file_request.html.erb
<%= render :partial => 'embeddeds/iframe', locals: { sign_url: @sign_url } %>

app/views/embeddeds/index.html.erb
<h1>HelloSign Embedded Workflows</h1>

<h4>Embedded Signing</h4>
<ul>
  <li>
    <%= link_to 'Sign with Template', embeddeds_template_path %>
  </li>
  <li>
    <%= link_to 'Sign with File', embeddeds_file_request_path %>
  </li>
</ul>
<h4>Embedded Requesting</h4>
<ul>
  <li>
    <%= link_to 'Unclaimed Draft Request with File', embeddeds_unclaimed_draft_path %>
  </li>
  <li>
    <%= link_to 'Unclaimed Draft Request with Template', embeddeds_unclaimed_draft_template_path %>
  </li>
</ul>
<h4>Embedded Templates</h4>
<ul>
  <li>
    <%= link_to 'Template Draft', embeddeds_template_draft_path %>
  </li>
  <li>
    <%= link_to 'Edit and Resend Unclaimed Draft', embeddedds_edit_unclaimed_draft_path %>
  </li>
</ul>
<p>
  <%= link_to 'Home', root_path %>
</p>

app/views/embeddeds/template.html.erb
<%= render :partial => 'embeddeds/iframe', locals: { sign_url: @sign_url, client_id: @client_id } %>

app/views/embeddeds/template_draft.html.erb
<%= render :partial => 'embeddeds/iframe', locals: { sign_url: @sign_url } %>

app/views/embeddeds/unclaimed_draft.html.erb
<%= render :partial => 'embeddeds/iframe', locals: { sign_url: @sign_url } %>

app/views/embeddeds/unclaimed_draft_template.html.erb
<%= render :partial => 'embeddeds/iframe', locals: { sign_url: @sign_url } %>